[package]
name = "learn-bevy-cube-of-cubes"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
