[package]
name = "learn-bevy-cube-of-cubes"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.0", features = ["dynamic_linking"] }
# bevy_flycam = "*"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
